"""
services/quickscan.py
======================
"""

import json
import logging
from urllib.parse import urlparse

import redis

from config import settings
from database.models import Scan
from risk_fusion import run_risk_fusion
from schemas.quick_scan import QuickScanRequest, QuickScanResponse, RiskLevel

logger = logging.getLogger(__name__)

_redis_client = redis.from_url(settings.REDIS_URL)

_CACHE_TTL_SECONDS = 300


def _domain_from_url(url: str) -> str:
    return urlparse(url).netloc or url


def _cache_key(domain: str) -> str:
    return f"quickscan:{domain}"


async def run_quickscan(payload: QuickScanRequest, user, db) -> QuickScanResponse:
    url = str(payload.url)
    domain = _domain_from_url(url)

    cached_raw = _redis_client.get(_cache_key(domain))
    if cached_raw:
        cached = json.loads(cached_raw)
        cached["url"] = url
        cached["domain"] = domain
        cached["cached"] = True
        return QuickScanResponse(**cached)

    is_whitelisted = False

    if is_whitelisted:
        risk_score = 0.0
        risk_level = RiskLevel.SAFE
        reasons = ["Domain is on the trusted allowlist."]
    else:
        result = run_risk_fusion({"url": url, "domain": domain})
        risk_score = result["risk_score"]
        risk_level = RiskLevel(result["risk_level"])
        reasons = [
            "Score generated by placeholder model (LightGBM not yet wired in)."
        ]

    scan = Scan(
        user_id=user.id,
        url=url,
        status="quick_scan_done",
        risk_score=risk_score,
        severity=risk_level.value if risk_level != RiskLevel.SAFE else None,
    )
    db.add(scan)
    db.commit()

    response = QuickScanResponse(
        url=url,
        domain=domain,
        risk_level=risk_level,
        risk_score=risk_score,
        is_whitelisted=is_whitelisted,
        cached=False,
        reasons=reasons,
    )

    _redis_client.setex(
        _cache_key(domain),
        _CACHE_TTL_SECONDS,
        response.model_dump_json(),
    )

    return response
