"""
services/quickscan.py
======================
Quick scan service: synchronous pre-flight threat assessment.

Security hardening (findings #1 & #2):
  - is_placeholder is mapped from the risk fusion result onto the response
    schema so the browser extension can render a neutral state.
  - Placeholder scores are NOT written to Redis cache (finding #2 fix):
    caching a random number would create a false consistency loop where
    every request for that domain within the TTL window receives the same
    fabricated score, giving an artificial appearance of determinism.
  - Only real, non-placeholder verdicts are cached. The cache TTL for real
    verdicts is kept at 5 minutes here (Stage 1 preliminary); the full
    1-hour cache is written by Risk Fusion (Stage 4) after the complete
    pipeline completes.
"""

import json
import logging
from urllib.parse import urlparse

import redis

from config import settings
from database.models import Scan
from risk_fusion import run_risk_fusion
from schemas.quick_scan import QuickScanRequest, QuickScanResponse, RiskLevel

logger = logging.getLogger(__name__)

_redis_client = redis.from_url(settings.REDIS_URL)

# Stage-1 preliminary cache TTL (5 min).
# Stage-4 Risk Fusion overwrites with the authoritative 1-hour verdict.
_CACHE_TTL_SECONDS = 300


def _domain_from_url(url: str) -> str:
    return urlparse(url).netloc or url


def _cache_key(domain: str) -> str:
    return f"quickscan:{domain}"


async def run_quickscan(payload: QuickScanRequest, user, db) -> QuickScanResponse:
    url = str(payload.url)
    domain = _domain_from_url(url)

    # ── Redis cache check ──────────────────────────────────────────────────
    # Only real verdicts are stored here (see caching logic below), so a
    # cache hit always contains a trustworthy is_placeholder=False result.
    cached_raw = _redis_client.get(_cache_key(domain))
    if cached_raw:
        cached = json.loads(cached_raw)
        cached["url"] = url
        cached["domain"] = domain
        cached["cached"] = True
        return QuickScanResponse(**cached)

    domain_lower = domain.lower()
    is_whitelisted = any(
        domain_lower == td or domain_lower.endswith("." + td)
        for td in getattr(settings, "TRUSTED_ALLOWLIST_DOMAINS", [])
    )

    if is_whitelisted:
        risk_score = 0.0
        risk_level = RiskLevel.SAFE
        reasons = ["Domain is on the trusted allowlist."]
        is_placeholder = False
    else:
        result = run_risk_fusion({"url": url, "domain": domain})
        risk_score = result["risk_score"]
        risk_level = RiskLevel(result["risk_level"])
        is_placeholder = result.get("is_placeholder", True)  # fail-closed: unknown → placeholder
        reasons = result.get("explanations") or []
        if not reasons:
            if is_placeholder:
                reasons = ["Score generated by placeholder model — treat as unverified."]
            else:
                reasons = []

    scan = Scan(
        user_id=user.id,
        url=url,
        status="quick_scan_done",
        risk_score=risk_score,
        severity=risk_level.value if risk_level != RiskLevel.SAFE else None,
    )
    db.add(scan)
    db.commit()

    response = QuickScanResponse(
        url=url,
        domain=domain,
        risk_level=risk_level,
        risk_score=risk_score,
        is_whitelisted=is_whitelisted,
        cached=False,
        is_placeholder=is_placeholder,
        reasons=reasons,
    )

    # ── Security finding #2 fix: NEVER cache placeholder scores ────────────
    # Caching a random number would make every user who hits the same domain
    # within the TTL window receive the identical fabricated score, creating
    # a false appearance of deterministic confidence.
    # Only cache when is_placeholder is False (real model verdict).
    if not is_placeholder:
        _redis_client.setex(
            _cache_key(domain),
            _CACHE_TTL_SECONDS,
            response.model_dump_json(),
        )
    else:
        logger.debug(
            "[quickscan] Skipping Redis cache for %s — is_placeholder=True "
            "(random score must not be persisted as a real verdict)",
            domain,
        )

    return response
