"""
Risk Fusion Engine

TODO:
Replace the placeholder implementation with the trained
LightGBM model once it is available from the AI/ML team.
"""

import random

from config import settings

# Placeholder for the trained model
model = None


def load_model():
    """
    TODO:
    Load the trained LightGBM model.
    """
    global model

    if model is None:
        model = "MODEL_NOT_AVAILABLE"

    return model


def build_feature_vector(features):
    """
    TODO:
    Convert the collected features into the exact
    order expected by the trained model.
    """
    return features


def predict_probability(feature_vector):
    """
    TODO:
    Replace this placeholder with:
        model.predict_proba(feature_vector)
    """

    return round(random.uniform(0.0, 1.0), 2)


def get_risk_level(score):
    if score < settings.SAFE_THRESHOLD:
        return "SAFE"
    elif score < settings.LOW_THRESHOLD:
        return "LOW"
    elif score < settings.MEDIUM_THRESHOLD:
        return "MEDIUM"
    elif score < settings.HIGH_THRESHOLD:
        return "HIGH"
    return "CRITICAL"


def run_risk_fusion(features):
    

    load_model()

    feature_vector = build_feature_vector(features)

    probability = predict_probability(feature_vector)

    risk_score = round(probability * 100, 2)

    return {
        "risk_score": risk_score,
        "risk_level": get_risk_level(risk_score),
        "probability": probability,
    }


class RiskFusionEngine:
    """


    TODO (AI/ML team): once the trained LightGBM model is available,
    build_feature_vector() below needs to assemble the *exact* ordered
    vector it expects. Until then this returns a random score, same as
    run_risk_fusion() - do not treat CRITICAL/HIGH results from this as
    real signal.
    """

    def compute(
        self,
        cyberintel: dict,
        browser_features: dict,
        sandbox_features: dict,
        consistency_report: dict,
    ) -> dict:
        merged_features = {
            "cyberintel": cyberintel or {},
            "browser_features": browser_features or {},
            "sandbox_features": sandbox_features or {},
            "consistency_report": consistency_report or {},
        }

        result = run_risk_fusion(merged_features)

        explanations = self._build_explanations(merged_features, result)

        return {
            "risk_score": result["risk_score"],
            "severity": result["risk_level"],
            "probability": result["probability"],
            "explanations": explanations,
            "iocs": merged_features["cyberintel"].get("iocs", []),
        }

    def _build_explanations(self, merged_features: dict, result: dict) -> list:
        explanations = []

        consistency_report = merged_features["consistency_report"]
        if consistency_report.get("cloaking_suspected"):
            explanations.append("Cloaking suspected: browser and sandbox views disagree.")

        mismatches = consistency_report.get("mismatches") or []
        if mismatches:
            explanations.append(f"Consistency mismatches: {', '.join(mismatches)}.")

        if model == "MODEL_NOT_AVAILABLE":
            explanations.append(
                "Score generated by placeholder model (LightGBM not yet wired in)."
            )

        return explanations
