"""Add sandbox telemetry tables

Revision ID: d2575a9c427f
Revises: d9a23b567890
Create Date: 2026-07-18 21:46:21.058283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2575a9c427f'
down_revision: Union[str, Sequence[str], None] = 'd9a23b567890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downloads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_downloads_scan_id'), 'downloads', ['scan_id'], unique=False)
    op.create_table('evasion_techniques',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('technique_name', sa.String(length=128), nullable=False),
    sa.Column('evidence_snippet', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evasion_techniques_scan_id'), 'evasion_techniques', ['scan_id'], unique=False)
    op.create_table('form_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('action_url', sa.String(length=2048), nullable=True),
    sa.Column('input_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_password_field', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_metrics_scan_id'), 'form_metrics', ['scan_id'], unique=False)
    op.create_table('network_activity',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_activity_domain'), 'network_activity', ['domain'], unique=False)
    op.create_index(op.f('ix_network_activity_ip_address'), 'network_activity', ['ip_address'], unique=False)
    op.create_index(op.f('ix_network_activity_scan_id'), 'network_activity', ['scan_id'], unique=False)
    op.create_table('redirects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('from_url', sa.String(length=2048), nullable=False),
    sa.Column('to_url', sa.String(length=2048), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redirects_scan_id'), 'redirects', ['scan_id'], unique=False)
    op.create_table('tls_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('protocol', sa.String(length=64), nullable=True),
    sa.Column('cipher', sa.String(length=128), nullable=True),
    sa.Column('issuer', sa.String(length=512), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
    sa.Column('cert_chain', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tls_connections_domain'), 'tls_connections', ['domain'], unique=False)
    op.create_index(op.f('ix_tls_connections_scan_id'), 'tls_connections', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tls_connections_scan_id'), table_name='tls_connections')
    op.drop_index(op.f('ix_tls_connections_domain'), table_name='tls_connections')
    op.drop_table('tls_connections')
    op.drop_index(op.f('ix_redirects_scan_id'), table_name='redirects')
    op.drop_table('redirects')
    op.drop_index(op.f('ix_network_activity_scan_id'), table_name='network_activity')
    op.drop_index(op.f('ix_network_activity_ip_address'), table_name='network_activity')
    op.drop_index(op.f('ix_network_activity_domain'), table_name='network_activity')
    op.drop_table('network_activity')
    op.drop_index(op.f('ix_form_metrics_scan_id'), table_name='form_metrics')
    op.drop_table('form_metrics')
    op.drop_index(op.f('ix_evasion_techniques_scan_id'), table_name='evasion_techniques')
    op.drop_table('evasion_techniques')
    op.drop_index(op.f('ix_downloads_scan_id'), table_name='downloads')
    op.drop_table('downloads')
    # ### end Alembic commands ###
